### PR TITLE
Migrate to specs2-3.6.2

### PR DESCRIPTION
**Pull request by fr3akX**

### CODE REVIEW

**Comment by athieriot** [comment]
Hello !

   Thank you for the Pull Request :)
   This seems great. I don't have much time to maintain it but I'm happy to deploy the version to Sonatype when needed.

   Could you just take a look at fixing the build please? 
   Apparently the version of SBT we were using (1.3.0) is not available any more. Switching to 1.3.9 should probably be enough to fix that and go through the actual tests.

   It would be really sweet to squash your commits as well but it's optional ;)

   Also, as you made the project compatible with ReactiveMongo, you surely are entitled to bump the version number to 0.8.0 :) (Maybe adding a line about it in the Readme if you fancy).
   I'll do it anyway after the merge but you might prefer to do it yourself. Up to you.

Thank you again

**Comment by mtraina** [comment]
Hi guys,
Good work on this project!
Any news about the merge of this pull request? It looks like that the only available version is still 0.7.0.

Cheers.

**Comment by athieriot** [comment]
Hi @mtraina,

Thank you for your interest.

I don't have much time at the moment and this PR seems quite old now to be honest.
Would you be interested in following on @fr3akX work?

If you are willing to propose a PR that doesn't fail the build I would be happy to merge it and release a new version.

**Comment by mtraina** [comment]
Hi @athieriot,
I continued from the changes of @fr3akX and made some changes, have a look to the PR, please.

Thanks.

**Comment by athieriot** [comment]
Fixed by #18

**Pull request closed without merging**
